# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/quarto_test',
                'doc_host': 'https://zsiegel92.github.io',
                'git_url': 'https://github.com/zsiegel92/quarto_test',
                'lib_path': 'quarto_test'},
  'syms': {'quarto_test.core': {'quarto_test.core.foo': ('core.html#foo', 'quarto_test/core.py')}}}
